# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        date

# Setup
title:            'Choens'
tagline:          '(Nullius in verba)'
description:

baseurl:          
url:              'https://choens.github.io/'
  
author:
  name:           'Andy Choens'
  email:          andy.choens@gmail.com
  url:            https://choens.github.io
  linkedin:       https://www.linkedin.com/in/andrew-choens-5639321b
  phone:          '518-275-5984'

paginate:         7
paginate_path:    /page:num

# Custom vars
version:          1.9.9

github:
  repo:           https://github.com/choens.github.io
