# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        date

# Setup
title:            'Choens'
tagline:          'Nullius in verba'
description:      'Rambling about technology, bikes, research and family'
url:              https://choens.github.io
baseurl:          

author:
  name:           'Andy Choens'
  email:          andy.choens@gmail.com
  url:            https://choens.github.io
  linked-in:      https://www.linkedin.com/in/andrew-choens-5639321b

paginate:         7
paginate_path:    /page:num

# Custom vars
version:          1.9.9

github:
  repo:           https://github.com/choens.github.io
