## Setup
title: Andy's Adventures
tagline: Just another blog focused on Adventures, Analytics and Family.
description: Stuff I want to say.
markdown: kramdown

pages_list:       
  About: '/about'
  Blog: '/blog'
  RSS: '/rss.xml'

##url:choens.github.io

## About Me
author :
    name : Andy Choens
    email : andy.choens@gmail.com
    github : Choens

