## Site ========================================================================
url: https://choens.github.io
name: Andy's Blog
description: Nullius in verba.

# What exactly does this do?
#pages_list:       
#  About: '/about'
#  Blog: '/blog'
#  RSS: '/rss.xml'



## About Me ====================================================================
author: Andy Choens
email: andy.choens@gmail.com
github: Choens



## Config ======================================================================

# Markdown engine --------------------------------
markdown: rdiscount

# Makes pretty (descriptive) permalinks ----------
# See Jekyll docs for alternatives.
permalink: pretty

# N articles to appear on the front page ---------
paginate: 7

# Exclude ----------------------------------------
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Gems -------------------------------------------
gems: [jekyll-paginate]
